### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'getBookData' in Worksheet.ipynb

### ISSUE THREAD

**Issue by shrik450** [Auquan/qq-optiver#3]
![Screenshot.](https://user-images.githubusercontent.com/13411240/44588549-a9974000-a7d3-11e8-84a6-29a2acaf5b10.png)

With auquan Toolbox v 2.1,3.

**Comment by nikhilnandyala97** [comment]
Same error is coming for me to.

**Comment by chandinijain** [comment]
@shrik450 @nikhilnandyala97 

fixed, please remove the `.getBookData()` bit, so change to
prices[i] = DataDictByInstrument[i][price]

you'll have to make this change in the next cell as well.

OR
Just re-download the file :)
